// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app) {
    var login, logout, signup, start;
    login = require('./login')(app);
    logout = require('./logout')(app);
    start = require('./start')(app);
    signup = require('./signup')(app);
    return [login, logout, start, signup];
  };

}).call(this);
