// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  module.exports = function(app) {
    var router;
    router = express.Router();
    router.post('/login', function(req, res, next) {
      return app.models.User.login(req.body).then(function(user) {
        var cookieName, cookieOptions, renderedUser, session;
        renderedUser = user.render().user;
        session = renderedUser.session;
        cookieName = app.options.frontend.cookie.name;
        cookieOptions = app.options.frontend.cookie.options;
        res.cookie(cookieName, session, cookieOptions);
        return res.redirect('/');
      })["catch"](function(err) {
        return app.error(res, err);
      });
    });
    return router;
  };

}).call(this);
