// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  module.exports = function(app) {
    var router;
    router = express.Router();
    router.get('/', function(req, res, next) {
      var data, failed, session;
      failed = false;
      data = {};
      if (req.cookies == null) {
        failed = true;
      } else {
        session = req.cookies[app.options.frontend.cookie.name];
      }
      if (!session) {
        failed = true;
      }
      if (failed) {
        return res.status(403).end();
      }
      return app.models.User.findBySession(session).then(function(user) {
        if (!user) {
          throw new Error('User was not found');
        }
        data = user.render();
        return res.render('start', data);
      })["catch"](function(err) {
        return app.error(res, err);
      });
    });
    return router;
  };

}).call(this);
