// Generated by CoffeeScript 1.7.1
(function() {
  var fs, models, path;

  fs = require('fs');

  path = require('path');

  models = {};

  module.exports = function(db) {
    fs.readdirSync(__dirname).filter(function(file) {
      return (file.indexOf('.') !== 0) && (file !== 'index.js') && (file.indexOf('.js') !== -1);
    }).forEach(function(file) {
      var model;
      model = db["import"](path.join(__dirname, file));
      return models[model.name] = model;
    });
    return models;
  };

}).call(this);
