// Generated by CoffeeScript 1.7.1
(function() {
  var _;

  _ = require('lodash');

  module.exports = function(app) {
    var login, signup, time;
    login = require('./login')(app);
    signup = require('./signup')(app);
    time = require('./time/index')(app);
    app.param('userId', function(req, res, next, id) {
      return app.models.User.load(id).then((function(_this) {
        return function(user) {
          if (!user) {
            return res.status(403).end();
          }
          req.user = user;
          return next();
        };
      })(this));
    });
    return [login, signup];
  };

}).call(this);
