// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  module.exports = function(app) {
    var listUsers, router;
    router = express.Router();
    listUsers = function(req, res, next) {
      return app.models.user.signup(req);
    };
    router.get('/users', listUsers);
    return router;
  };

}).call(this);
